### ISSUE TITLE
Packagist support

### ISSUE THREAD

**Issue by teppokoivula** [msaari/relevanssi-premium-snowball-stemmer#3]
Hey @msaari!

Any chance of getting this plugin to packagist? We'd love to use it in a project, but also would prefer to avoid custom composer configs for individual packages. Adding it to packagist.org would be super nice :)

Thanks for considering!

**Comment by msaari** [comment]
Well that took about five seconds: https://packagist.org/packages/msaari/relevanssi-premium-snowball-stemmer.

**Comment by teppokoivula** [comment]
Awesome, thank you!
